@url = http://localhost:3045

### BASE ROUTE
{{url}}

### LOGIN HENDRICK
POST {{url}}/login
content-type: application/json
 
{
    "username": "Sevde",
    "password": "123456"
}

### LOGIN ANDREA
POST {{url}}/login
content-type: application/json
 
{
    "username": "Ömer",
    "password": "123456"
}

### GET CURRENT USER
{{url}}/current-user

### LOGOUT GET 
{{url}}/logout